apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-server
  template:
    metadata:
      labels:
        app: llm-server
    spec:
      containers:
      - name: llm-server
        image: 575108933149.dkr.ecr.ap-northeast-2.amazonaws.com/bombi/llm:3
        ports:
        - containerPort: 8182
        env:          
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: GCS_CREDENTIAL
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: OPEN_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: DATASET_ID
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: TABLE_ID
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: AUTH_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: llm-server-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /llm/base/health
spec:
  selector:
    app: llm-server
  ports:
  - protocol: TCP
    port: 8182
    targetPort: 8182
