apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-server
  template:
    metadata:
      labels:
        app: llm-server
    spec:
      nodeSelector:
        intent: control-apps
      containers:
      - name: llm-server
        image: 575108933149.dkr.ecr.ap-northeast-2.amazonaws.com/bombi/llm:77
        ports:
        - containerPort: 8182
        env:          
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: DB_HOST
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: DB_PORT
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: DB_NAME
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: DB_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: DB_PASS
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: GCP_PROJECT_ID
        - name: GCS_CREDENTIAL
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: GCS_CREDENTIAL
        - name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: GOOGLE_APPLICATION_CREDENTIALS
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: JWT_SECRET
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: JWT_ALGORITHM
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: OPEN_API_KEY
        - name: DATASET_ID
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: DATASET_ID
        - name: TABLE_ID
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: TABLE_ID
        - name: AUTH_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: AUTH_SERVER_URL
---
apiVersion: v1
kind: Service
metadata:
  name: llm-server-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /llm/base/health
spec:
  selector:
    app: llm-server
  ports:
    - protocol: TCP
      port: 8182
      targetPort: 8182
