apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-server
  template:
    metadata:
      labels:
        app: llm-server
    spec:
      containers:
      - name: llm-server
        image: 575108933149.dkr.ecr.ap-northeast-2.amazonaws.com/bombi/llm:1
        ports:
        - containerPort: 8182
        env:                         
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/gcp/credentials.json"
        # - name: DB_HOST
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-credentials
        #       key: host
        # - name: DB_PORT
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-credentials
        #       key: port
        # - name: DB_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-credentials
        #       key: username
        # - name: DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-credentials
        #       key: password
        # - name: DB_NAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-credentials
        #       key: dbname
        - name: OPEN_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY  
        - name: GCP_PROEJECT_ID
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY            
        - name: TABLE_ID
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: AUTH_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: JWT_PUBLIC_KEY_PATH
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: llm-app-config
              key: MY_LLM_SECRET_KEY
        volumeMounts:
        - name: gcp-credentials
          mountPath: /secrets/gcp
          readOnly: true
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
      - name: gcp-credentials
        secret:
          secretName: gcp-credentials


---
apiVersion: v1
kind: Service
metadata:
  name: llm-server-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /llm/base/health
spec:
  selector:
    app: llm-server
  ports:
  - protocol: TCP
    port: 8182
    targetPort: 8182