apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: auth-server
          image: 575108933149.dkr.ecr.ap-northeast-2.amazonaws.com/bombi/auth:102
          ports:
            - containerPort: 8180
          resources:
            requests:
              cpu: "300m"      
              memory: "512Mi"
            limits:
              cpu: "700m"    
              memory: "1Gi"  
            
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: DB_PASS
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: GCP_PROJECT_ID
            - name: GCS_CREDENTIAL
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: GCS_CREDENTIAL
            - name: BIGQUERY_CREDENTIAL
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: BIGQUERY_CREDENTIAL
            - name: KAKAO_CLIENT_NAME
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: KAKAO_CLIENT_NAME
            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: KAKAO_CLIENT_ID
            - name: KAKAO_AUTH_METHOD
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: KAKAO_AUTH_METHOD
            - name: KAKAO_REDIRECT_ID
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: KAKAO_REDIRECT_ID
            - name: KAKAO_AUTH_TYPE
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: KAKAO_AUTH_TYPE
            - name: KAKAO_SCOPE
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: KAKAO_SCOPE
            - name: KAKAO_AUTH_URI
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: KAKAO_AUTH_URI
            - name: KAKAO_TOKEN_URI
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: KAKAO_TOKEN_URI
            - name: KAKAO_ATTRIBUTE
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: KAKAO_ATTRIBUTE
            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: KAKAO_CLIENT_SECRET
            - name: KAKAO_USER_INFO_URI
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: KAKAO_USER_INFO_URI
            - name: DDL_TYPE
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: DDL_TYPE
            - name: REDIS_PORT
              value: "6379"  # 하드코딩된 값 사용
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: REDIS_HOST
            - name: AUTH_PORT
              value: "8180"  # 하드코딩된 값 사용
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spring-app-config
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: auth-server-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /auth/health
spec:
  selector:
    app: auth-server
  ports:
    - protocol: TCP
      port: 8180
      targetPort: 8180
