apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-server-dep
  labels:
    app: core-server
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: core-server
  template:
    metadata:
      labels:
        app: core-server
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: core-server-container
        image: 575108933149.dkr.ecr.ap-northeast-2.amazonaws.com/bombi/core:7
        ports:
        - containerPort: 8181
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY 
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY            
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY  
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY
        - name: NAVER_ID
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY
        - name: NAVER_SECRET
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY
        - name: NAVER_NEWS_URL
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY
        - name: GCS_CREDENTIAL
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY
        - name: BIGQUERY_CREDENTIAL
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY
        - name: AUTH_URL
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: MY_CORE_SECRET_KEY


---
apiVersion: v1
kind: Service
metadata:
  name: core-server-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /core/health
spec:
  selector:
    app: core-server
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
