apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-server-dep
  labels:
    app: core-server
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: core-server
  template:
    metadata:
      labels:
        app: core-server
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        intent: control-apps
      containers:
      - name: core-server-container
        image: 575108933149.dkr.ecr.ap-northeast-2.amazonaws.com/bombi/core:44
        ports:
        - containerPort: 8181
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: DB_PASS
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: REDIS_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: JWT_SECRET
        - name: NAVER_ID
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: NAVER_ID
        - name: NAVER_SECRET
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: NAVER_SECRET
        - name: NAVER_NEWS_URL
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: NAVER_NEWS_URL
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: GCP_PROJECT_ID
        # - name: GCS_CREDENTIAL
        #   valueFrom:
        #     secretKeyRef:
        #       name: core-app-config
        #       key: GCS_CREDENTIAL
        - name: BIGQUERY_CREDENTIAL
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: BIGQUERY_CREDENTIAL
        - name: AUTH_URL
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: AUTH_URL
        - name: SOIL_API_KEY
          valueFrom:
            secretKeyRef:
              name: core-app-config
              key: SOIL_API_KEY     
        - name: CORE_PORT
          value: "8181"        

---
apiVersion: v1
kind: Service
metadata:
  name: core-server-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /core/health
spec:
  selector:
    app: core-server
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
