apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-server-dep
  labels:
    app: front-server
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: front-server
  template:
    metadata:
      labels:
        app: front-server
    spec:
      containers:
      - name: front-server-container
        image: 575108933149.dkr.ecr.ap-northeast-2.amazonaws.com/bombi/front:56
        ports:
        - containerPort: 8185
---
apiVersion: v1
kind: Service
metadata:
  name: front-server-service
spec:
  selector:
    app: front-server
  ports:
    - protocol: TCP
      port: 8185
      targetPort: 8185
